// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPpv_dkofMMeo8AzE6-CR5ar44qVNPrLo',
    appId: '1:920232777173:web:26be8a0831ef037eaad95c',
    messagingSenderId: '920232777173',
    projectId: 'ddm2025-fernandofelipemauricio',
    authDomain: 'ddm2025-fernandofelipemauricio.firebaseapp.com',
    storageBucket: 'ddm2025-fernandofelipemauricio.firebasestorage.app',
    databaseURL: 'https://ddm2025-fernandofelipemauricio-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5xCC8j3LFizo4ufdEa9Kd6Hfop0dMPgs',
    appId: '1:920232777173:android:f97e9b9a51c3024baad95c',
    messagingSenderId: '920232777173',
    projectId: 'ddm2025-fernandofelipemauricio',
    storageBucket: 'ddm2025-fernandofelipemauricio.firebasestorage.app',
    databaseURL: 'https://ddm2025-fernandofelipemauricio-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6b0bh6A-nV4aAwxTGdGQaMrJgAqJQkSo',
    appId: '1:920232777173:ios:3c781aa3f39fcddaaad95c',
    messagingSenderId: '920232777173',
    projectId: 'ddm2025-fernandofelipemauricio',
    storageBucket: 'ddm2025-fernandofelipemauricio.firebasestorage.app',
    iosBundleId: 'com.example.t4',
    databaseURL: 'https://ddm2025-fernandofelipemauricio-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6b0bh6A-nV4aAwxTGdGQaMrJgAqJQkSo',
    appId: '1:920232777173:ios:3c781aa3f39fcddaaad95c',
    messagingSenderId: '920232777173',
    projectId: 'ddm2025-fernandofelipemauricio',
    storageBucket: 'ddm2025-fernandofelipemauricio.firebasestorage.app',
    iosBundleId: 'com.example.t4',
    databaseURL: 'https://ddm2025-fernandofelipemauricio-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPpv_dkofMMeo8AzE6-CR5ar44qVNPrLo',
    appId: '1:920232777173:web:252ed215d1bc38d7aad95c',
    messagingSenderId: '920232777173',
    projectId: 'ddm2025-fernandofelipemauricio',
    authDomain: 'ddm2025-fernandofelipemauricio.firebaseapp.com',
    storageBucket: 'ddm2025-fernandofelipemauricio.firebasestorage.app',
    databaseURL: 'https://ddm2025-fernandofelipemauricio-default-rtdb.firebaseio.com',
  );
}
